version: 2
jobs:
  build:
    working_directory: /go/src/github.com/helm/pull-sizer
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.09.0-ce
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go test -v
      - run:
          name: build push image
          command: ./build.sh
  lint-charts:
    docker:
      - image: quay.io/helmpack/chart-testing:v1.1.0
    steps:
      - checkout
      - run:
          name: "lint chart"
          command: |
            chart_test.sh --config .testenv --no-install
      
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
              tags:
                only: /.*/
      - lint-charts
